spring.application.name=food-order-backend

spring.datasource.url=jdbc:mysql://localhost:3306/foodorderapp
spring.datasource.username=root
spring.datasource.password=Mohan@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true